# Generated by Django 6.1 on 2026-08-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_driver_latitude_order_driver_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dest_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dest_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Verification'), ('Accepted', 'Accepted / Packing'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
